### ISSUE TITLE
mqtt server bound to all interfaces

### ISSUE THREAD

**Issue by huornlmj** [greenbone/docs#397] opened 2023-09-29 17:25 UTC
https://github.com/greenbone/docs/blob/ba8fcefd522becb69cc853f274372860f09d736b/src/_static/docker-compose-22.4.yml#L140

The deployment results in the mqtt service binding to all interfaces, allowing network adversaries to access the service, when it should not be exposed outside the host.

**Comment by bjoernricks** [comment] 2023-10-02 08:02
Duplicate of  #366

**Closed by bjoernricks** 2023-10-02 08:02 UTC

**Comment by huornlmj** [comment] 2023-10-02 09:25
Why is this closed?  The port is open and the issue is not fixed.

**Comment by bjoernricks** [comment] 2023-10-02 09:35
Because the PR is merged in the MQTT port is not exposed to the host interface anymore.

**Comment by huornlmj** [comment] 2023-10-02 09:48
Oh I found PR #401 now.  Assuming it passed tests?

**Comment by bjoernricks** [comment] 2023-10-02 09:52
> Assuming it passed tests?

Not sure what you mean. Removing the ports statement from the compose file will remove the exposed port from the host interfaces. Could be possible that you need to recreate the containers (compose down, compose up).
